name: NEW Style PR
description: Title for a yaml PR
title: "[#123] <title>"
body:
- type: textarea
  attributes:
    label: Issue No
    description: Do NOT open a PR without discussing the changes on an open issue, first.
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Contribution Guidelines
    options:
    - label: I have read the [Contribution Guidelines](../Contribution.md)
      required: true
- type: checkboxes
  attributes:
    label: Changes were discussed
    options:
    - label: I have commented on the issue above and discussed the intended changes
      required: true
- type: checkboxes
  attributes:
    label: issue is assigned
    options:
    - label: A maintainer has signed off on the changes and the issue was assigned to me
      required: true
- type: checkboxes
  attributes:
    label: Tests were added
    options:
    - label: All newly added code is adequately covered by tests
      required: true
- type: checkboxes
  attributes:
    label: All tests are still running
    options:
    - label: All existing tests are still running without errors
      required: true
- type: checkboxes
  attributes:
    label: Documentation
    options:
    - label: The documentation was modified to reflect the changes _OR_ no documentation changes are required.
      required: true
- type: textarea
  id: description
  attributes:
    label: Description
    placeholder: describe the changes you made.
  validations:
    required: true

